= boot-bowdlerize

Thomas Bowdler infamously excised the naughty bits in Shakespeare,
producing a sanitized -- _bowdlerized_ -- version of the Bard for
children and the those whose sensibilities were offended by obscene
language.  `boot-bowdlerize` tries to do the same for `bower`,
excising those nasty bits bits of Javascript and JSON to produce a
Clojurized version suitable for those offended by obscene languages.

`boot-bowdlerize` is not tied to bower, however.  It's really a an
implementation of a simple technique for generating namespaced runtime
configuration information at build-time.

You can think of `boot-bowdlerize` as a meta-configuration tool.  Or a
meta-package-manager.

== motivation

Webapp development requires coordination between filesystem
configuration (location and structure of resource directories, etc.)
and app configuration (using filesystem paths in <link> elements, for
example.)  You might also want to use build config info at runtime,
e.g. you might want to have an `admin` webpage that dumps version info
about dependencies, tools, etc. used to build the app.

Goals:

* use indirection, so e.g. if you change your filesystem layout you only have to change config info in one place

* keep all config info in one place at build time, but:

* use namespaces to partition runtime config data, rather than putting
  everything into on giant config map

* make config info available at both build time and compile time

* dynamically generate runtime config info at build time where possible, e.g. pull version info from resource metadata instead of hardcoding it

* etc.


WARNING: BREAKING CHANGES: configurations are now written in `.edn`
files and the data format has changed.  The documentation here is
out-of-date with respect to details although the overall design is
pretty much the same.  See the link:webjars/[webjars] testapp for the most
up-to-date config examples.

== usage

Fork/clone this project, install `tasklib`, and build and run `jetty`.
See the READMEs in those subdirs.

The basic idea is that we define config data in ordinary clojure
namespaces (source files), and at build time we use those namespaces
to generate runtime config source files.  One way to do this,
illustrated by the testapps in this project, is to use a `config`
directory on the classpath to hold build-time config specs.


=== bower

An example of such a file for bower resources follows.
`boot-bowdlerize` uses the bower package name to install it and read
its metadata, so our config maps uses package names as keys.  You can
use any names for both namespace and interned syms; you will list them
in your `build.boot` file, as explained below.  In this example, the
`moment` package metadata has enough information for use to extract
the resource URI automatically, so all we need to provide is the
symbol we want to use for it at runtime.  But the `materialize`
package bundles several components, and its metadata is not
sufficiently rich to support inference to their URIs.  So we have to
explicitly indicate them in the `:bundles` maps.

WARNING: out of date, syntax is changing

[source,clojure]
.bower.edn
----
[{:bower "moment"
  :runtime 'hello.scripts/moment}
 {:bower "underscore"
  :runtime 'hello.scripts/underscore}]
----

=== polymer

`boot-bowdlerize` began life as a tool to help write
https://www.polymer-project.org/1.0/[Polymer] webapps in Clojure.

A sample Polymer app may be found in the `polymer` subdirectory.

NOTE: up-to-date

[source,clojure]
.polymer.edn
----
;; syntax:
;; {<app-ns-sym> {<app-var-sym> <bower pkg>}}

{polymer.iron {icon "PolymerElements/iron-icon"
               icons "PolymerElements/iron-icons"
               input "PolymerElements/iron-input"}
 polymer.paper {button "PolymerElements/paper-button"
                card "PolymerElements/paper-card"
                input "PolymerElements/paper-input"}

 ;; for bundled web components (with html tag):
 ;; {<app-ns-sym> {:bower <bower pkg>
 ;;                <app-var-sym> {<html-tag> <bower-repo-url>}}}
 polymer.paper.input {:bower "PolymerElements/paper-input"
                      textarea {:paper-textarea "bower_components/paper-input/paper-textarea.html"}
                      behavior {:paper-input-behavior
                                "bower_components/paper-input/paper-input-behavior.html"}
                      container {:paper-input-container
                                 "bower_components/paper-input/paper-input-container.html"}
                      error {:paper-input-error
                             "bower_components/paper-input/paper-input-error.html"}
                      addon-behavior {:paper-input-addon-behavior
                                      "bower_components/paper-input/paper-input-addon-behavior.html"}
                      char-counter {:paper-input-char-counter
                                    "bower_components/paper-input/paper-input-char-counter.html"}}

 ;; for bundled resources (not web components, no html tag):
 ;; {<app-ns-sym> {:bower <bower pkg>
 ;;                <app-var-sym> <bower-repo-url>}}
 polymer.polyfill {:bower "webcomponentsjs"
                   heavy "bower_components/webcomponentsjs/webcomponents.js"
                   lite "bower_components/webcomponentsjs/webcomponents-lite.js"}
 polymer.polyfill.min {:bower "webcomponentsjs"
                       heavy "bower_components/webcomponentsjs/webcomponents.min.js"
                       lite "bower_components/webcomponentsjs/webcomponents-lite.min.js"}}
----


=== webjars

NOTE: up-to-date


[source,clojure]
----
;; syntax:
;; {<app-ns-sym> {<app-var-sym> [<webjars coordinates>]}}

{polymer.paper {button [org.webjars.bower/github-com-PolymerElements-paper-button "1.0.11"]
                card [org.webjars.bower/github-com-PolymerElements-paper-card "1.0.8"]}
 polymer.iron {icon [org.webjars.bower/github-com-PolymerElements-iron-icon "1.0.7"]
               icons [org.webjars.bower/github-com-PolymerElements-iron-icons "1.1.3"]}
 test {materialize [org.webjars.bower/materialize "0.97.5"]}
 npm {base64 [org.webjars.npm/Base64 "0.3.0"]}}
----

=== local resources

WARNING: out of date

You can also specify resources that do not rely on bower, e.g.

[source,clojure]
.resources.clj
----
(ns resources)
(def scripts
  [{:runtime 'hello.scripts/jquery
    :uri "https://code.jquery.com/jquery-2.1.1.min.js"}])
(def statics
  [{:runtime 'hello.resources/statics :uri "target"}])
(def styles
  [{:runtime 'hello.styles/app :uri "styles/app.css"}
   {:runtime 'hello.scripts/app :uri "scripts/app.js"}])
----

Here `resources/statics` is an example of using the `bowdlerize`
mechanism to specify a runtime configuration parameter rather than a
web resource.  In this case, our `jetty` testapp handler uses
`hello.resources/statics` to set the `:root` parameter of the
`route/files` function to "target".

You can organize your config maps however you please; for example
here's the same info, reorganized:

[source,clojure]
.hello-stuff.clj
----
(ns resources)
(def scripts
  [{:runtime 'hello.scripts/jquery :uri "https://code.jquery.com/jquery-2.1.1.min.js"}
   {:runtime 'hello.scripts/app :uri "scripts/app.js"}])
(def statics
  [{:runtime 'hello.resources/statics :uri "target"}])
(def styles
  [{:runtime 'hello.styles/app :uri "styles/app.css"}])
----

Notice that in the above example three runtime namespaces were used,
`hello.scripts`, `hello.styles`, and `hello.resources`.  You can use
any namespace, anywhere in any config file.  When `boot-bowlderize`
processes your build-time config files, it will merge them
appropriately, so in this case it will produce three runtime config
files:

[source,clojure]
.hello/resources.clj
----
(ns hello.resources)
(def statics {:uri "target"})
----

[source,clojure]
.hello/scripts.clj
----
(ns hello.scripts)
(def materialize {:uri "bower_components/Materialize/bin/materialize.js" :type :js})
(def moment {:uri "bower_components/moment/moment.js" :type :js})
(def app {:uri "scripts/app.js" :type :js})
(def jquery {:uri "https://code.jquery.com/jquery-2.1.1.min.js" :type :js})
----

[source,clojure]
.hello/styles.clj
----
(ns hello.styles)
(def materialize {:uri "bower_components/Materialize/bin/materialize.css" :type :css})
(def app {:uri "styles/app.css" :type :css})
----

You configure `boot-bowdlerize` to put these somewhere on your runtime
classpath so they become available to your app.  The default setting
puts them in `target/classes`.

=== build.boot

Here's how you configure your `build.boot`:

[source,clojure]
.build.boot
----
:dependencies '[ ... [mobileink/boot-bowdlerize "0.1.0-SNAPSHOT" :scope "test"] ...]
(require '[boot-bowdlerize :as b] ...)
;; define the set of config data vars; must be on build-time classpath
(def configs #{'resources/styles 'resources/scripts 'resources/statics 'bower/config-map})
;; pass the vars to bowdlerize tasks
(task-options!
 b/config {:nss configs}
 b/config-rm {:nss configs}  ;; prevents the buildtime sources from being copied to target
 b/install {:nss configs}
 ...
----

=== runtime

You're generating source files so you have to make sure to set your classpath correctly.

== experimenting

Try this with e.g. the gae sample app:

[source,shell]
----
$ boot b/bower b/resources show -f target
$ boot b/bower b/resources sift -i ".*bowdlerize.edn" -a ".*ize.edn" show -f target
----

The first command here will show that the hidden master edn file
`bowdlerize.edn` is in the fileset emitted by the `b/resources` task,
but it will not be written to the build dir by `target`.  That's
because `bowdlerize.edn` is marked for input but not output.  The
`b/bower` and `b/resources` tasks read it as an input file, and then
write it as an input file, but to a new fileset; remember that tasks
that make any changes pass a _new_ fileset to the following task.  The
`b/config` task, coming after the tasks that elaborate
`bowdlerize.edn`, reads it as an input and then writes it as an ouput,
after which target would write it.

So in order to inspect `bowdlerize.edn` you must run the tasks that
produce it and then change it to an output file before feeding it to
`target`.  That's what the `sift` task in the second command above
does.  The `-i` flag will include only those files matching its
(regex) argument; the `-a` flag will add whatever matches its regex to
the `assets` collection - those files marked for output.  The final
task in the pipeline will receive a fileset with a single file marked
for output: `bowdlerize.edn`.  This will print the hidden master edn
file to the target dir so you can inspect it.


== misc

link:https://github.com/wilmoore/frontend-packagers[fe packagers]
