(ns polymer)

(def config-map
  {"PolymerElements/iron-icon" 'miraj.iron/icon
   "PolymerElements/iron-icons" 'miraj.iron/icons
   "PolymerElements/paper-button" 'miraj.paper/button
   "PolymerElements/paper-card" {:ns 'miraj.paper :name 'card}
   "PolymerElements/paper-input" [{:ns 'miraj.paper
                                   :name 'input
                                   :kw :paper-input
                                   :polymer true
                                   :uri "bower_components/paper-input/paper-input.html"}
                                  {:ns 'miraj.paper.input
                                   :name 'textarea
                                   :kw :paper-textarea
                                   :polymer true
                                   :uri "bower_components/paper-input/paper-textarea.html"}
                                  {:ns 'miraj.paper.input
                                   :name 'behavior
                                   :kw :paper-input-behavior
                                   :polymer true
                                   :uri "bower_components/paper-input/paper-input-behavior.html"}
                                  {:ns 'miraj.paper.input
                                   :name 'container
                                   :kw :paper-input-container
                                   :polymer true
                                   :uri "bower_components/paper-input/paper-input-container.html"}
                                  {:ns 'miraj.paper.input
                                   :name 'error
                                   :kw :paper-input-error
                                   :polymer true
                                   :uri "bower_components/paper-input/paper-input-error.html"}
                                  {:ns 'miraj.paper.input
                                   :name 'addon-behavior
                                   :kw :paper-input-addon-behavior
                                   :polymer true
                                   :uri "bower_components/paper-input/paper-input-addon-behavior.html"}
                                  {:ns 'miraj.paper.input
                                   :name 'char-counter
                                   :kw :paper-input-char-counter
                                   :polymer true
                                   :uri "bower_components/paper-input/paper-input-char-counter.html"}]})
